package com.saas.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Represents a tenant (Organization) in the SaaS system.
 * Each organization has its own isolated database schema.
 * This entity resides in the master database (saas_db).
 */
@Entity
@Table(name = "organizations", catalog = "saas_db")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Organization {

    /** Unique identifier generated by Snowflake algorithm. */
    @Id
    private Long id;

    /** Display name of the organization. */
    @Column(nullable = false)
    private String name;

    /** Timestamp when the organization was provisioned. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
