package com.saas.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Represents a project within a workspace.
 * Projects group related todos.
 * This entity resides in the tenant-specific schema.
 */
@Entity
@Table(name = "projects")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Project {

    /** Unique identifier generated by Snowflake algorithm. */
    @Id
    private Long id;

    /** Name of the project. */
    @Column(nullable = false)
    private String name;

    /** The workspace this project belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "workspace_id", nullable = false)
    private Workspace workspace;

    /** Timestamp when the project was created. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
