package com.saas.backend.entity;

import com.saas.backend.enums.TodoPriority;
import com.saas.backend.enums.TodoStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Represents a task (Todo) within a project.
 * This entity resides in the tenant-specific schema.
 */
@Entity
@Table(name = "todos")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Todo {

    /** Unique identifier generated by Snowflake algorithm. */
    @Id
    private Long id;

    /** Title of the todo item. */
    @Column(nullable = false)
    private String title;

    /** Detailed description of the task. */
    @Column(columnDefinition = "TEXT")
    private String description;

    /** Current status (e.g., TODO, IN_PROGRESS, DONE). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TodoStatus status;

    /** Task priority (e.g., LOW, MEDIUM, HIGH). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TodoPriority priority;

    /** The user assigned to this task (resides in master schema). */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_user_id")
    private User assignedUser;

    /** The project this todo belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;

    /** Optional deadline for the task. */
    @Column(name = "due_date")
    private LocalDateTime dueDate;

    /** Timestamp when the todo was created. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
