package com.saas.backend.entity;

import com.saas.backend.enums.AuthProvider;
import com.saas.backend.enums.MembershipStatus;
import com.saas.backend.enums.Role;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Represents a user in the SaaS system.
 * Users belong to a specific organization and have a role that defines their
 * permissions.
 * This entity resides in the master database (saas_db).
 */
@Entity
@Table(name = "users", catalog = "saas_db")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /** Unique identifier generated by Snowflake algorithm. */
    @Id
    private Long id;

    /** Full name of the user. */
    @Column(nullable = false)
    private String name;

    /** Unique email address used for login. */
    @Column(nullable = false, unique = true)
    private String email;

    /** Encrypted password for local authentication. Null for OAuth users. */
    @Column(nullable = true)
    private String password;

    /** System role (e.g., ORG_ADMIN, USER). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    /** Authentication provider (LOCAL or GOOGLE). */
    @Enumerated(EnumType.STRING)
    @Column(name = "auth_provider", nullable = false)
    @Builder.Default
    private AuthProvider authProvider = AuthProvider.LOCAL;

    /** External identifier from the auth provider (e.g., Google sub). */
    @Column(name = "auth_provider_id")
    private String authProviderId;

    /** Status of the user's membership in the organization. */
    @Enumerated(EnumType.STRING)
    @Column(name = "membership_status", nullable = false)
    @Builder.Default
    private MembershipStatus membershipStatus = MembershipStatus.APPROVED;

    /** The organization this user belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "organization_id")
    private Organization organization;

    /** Timestamp when the user was created. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
