package com.saas.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Represents a workspace within a tenant.
 * Workspaces are top-level containers for projects and todos.
 * This entity resides in the tenant-specific schema.
 */
@Entity
@Table(name = "workspaces")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Workspace {

    /** Unique identifier generated by Snowflake algorithm. */
    @Id
    private Long id;

    /** Name of the workspace. */
    @Column(nullable = false)
    private String name;

    /** Timestamp when the workspace was created. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
